version: '3'
services:
  graph-node:
    container_name: graph-node
    image: graphprotocol/graph-node:v0.25.0
    ports:
      - '9000:8000'
      - '9001:8001'
      - '9020:8020'
      - '9030:8030'
      - '9040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: "spree:http://172.17.0.1:8545"
      GRAPH_LOG: info
  ipfs:
    container_name: nevermined-ipfs
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
  postgres:
    container_name: nevermined-postgres
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
