name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: nevermined-io/nvm-tools-actions@v0.9.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          node-version: 'develop'

      - name: Install dependencies
        run: yarn

      - name: Run graph-node
        run: |
          docker-compose up -d
          ./scripts/wait_for_graph.sh

      - name: copy-artifacts
        run: ./scripts/wait-nevermined.sh

      - name: Test update-addresses
        run: yarn nevermined:update-addresses geth-localnet
      - name: Test update-startblock
        run: OVERRIDE_SUBGRAPH_STARTING_BLOCK=10 yarn nevermined:update-startblock geth-localnet
      - name: Test update-network
        run: yarn nevermined:update-network spree
      - name: Test create
        run: yarn nevermined:create development geth-localnet v3
      - name: Test deploy
        run: yarn nevermined:deploy development geth-localnet v3
      - name: Unit tests
        env:
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
        run: yarn test
      - name: Test the clients compile
        run: yarn tsc
