name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: nevermined-io/nvm-tools-actions@v0.13.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          contracts-version: "v3.2.2"

      - name: Install dependencies
        run: yarn

      - name: Run graph-node
        run: |
          docker compose up -d
          ./scripts/wait_for_graph.sh

      - name: copy-artifacts
        run: nvm-tools copy-artifacts ./artifacts

      - name: Test update network
        run: yarn graph:update-network geth-localnet
      - name: Test create
        run: yarn graph:create-local development geth-localnet v3
      - name: Test deploy
        run: yarn graph:deploy-local development geth-localnet v3
      - name: Unit tests
        env:
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
        run: yarn test
