name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["--spree-embedded-contracts", "--polygon", "--geth"]
        include:
          - network: "--spree-embedded-contracts"
            network-name: spree
          - network: "--polygon"
            network-name: polygon-localnet
          - network: "--geth"
            network-name: "geth-localnet"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn
      # - name: Check linting
      #   run: yarn lint

      - name: Reclaim some disk space
        run: |
          docker system prune --all --volumes -f
      - name: Run tools (network)
        run: |
          docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
          sudo chmod go+r /etc/hosts
          sudo echo "127.0.0.1  nevermined-metadata" | sudo tee -a /etc/hosts
          git clone https://github.com/nevermined-io/tools
          cd tools
          export KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"
          rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"

          ./start_nevermined.sh --latest --no-graph ${{ matrix.network }} &
          cd ..
          ./scripts/wait-nevermined.sh

      - name: Run graph-node
        run: |
          docker-compose up -d
          ./scripts/wait_for_graph.sh

      - name: Test update-addresses
        run: yarn nevermined:update-addresses ${{ matrix.network-name }}
      - name: Test update-startblock
        run: OVERRIDE_SUBGRAPH_STARTING_BLOCK=10 yarn nevermined:update-startblock ${{ matrix.network-name }}
      - name: Test update-network
        run: yarn nevermined:update-network spree
      - name: Test create
        run: yarn nevermined:create development ${{ matrix.network-name }} v200
      - name: Test deploy
        run: yarn nevermined:deploy development ${{ matrix.network-name }} v200
      - name: Unit tests
        env:
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
        run: yarn test
      - name: Test the clients compile
        run: yarn tsc
